# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.2.1'
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^site/
    -   id: end-of-file-fixer
        exclude: ^site/
    -   id: check-yaml
        exclude: ^site/|conf/deployment.yml
    -   id: check-added-large-files
        exclude: ^site/
-   repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
    -   id: pip-compile
        name: pip-compile pyproject.toml
        files: ^pyproject.toml$
        args: [pyproject.toml, --extra=dev, --output-file=requirements_dev.txt, --annotation-style=line, --no-emit-trusted-host, --no-emit-index-url, --allow-unsafe, --resolver=backtracking]
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        files: ^notebooks/|^ae_utils/|requirements_dev.txt|requirements.txt
