site_name: causalAssembly Doku

theme:
    name: material
    custom_dir: overrides

extra:
    version:
        default: latest
        provider: mike

plugins:
    - mkdocstrings
    - mike:
        canonical_version: latest

nav:
    - index.md
    - documentation.md

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
